# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 557a6c529a5bab3385e702ddd2f4f69fb8407900385c901909756149447bfc6b3c511dade46e061ba1a0d3e6a284021d30f4e25f1576a05e965a2c527c09ebe3

test:
  secret_key_base: 8fadfea5f9108344553b7e959db232966243eff6398cbf8f73bddb47f156f02c8d0f28798ecc7d5598fa15d6c7b1da084dd4e40dc3a49bb8f8b875902cfaa294

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
